name: SurvivalCore
version: '${version}'
main: pl.championsmp.survivalcore.SurvivalCore
api-version: '1.21'
author: ChampionSMP
description: Core plugin dla serwera ChampionSMP.pl

commands:
  register:
    description: Rejestracja konta gracza.
    usage: /register <haslo> <powtórzHaslo> <kod>

  login:
    description: Logowanie do konta gracza.
    usage: /login <haslo>

  sklep:
    description: Otwiera menu sklepu.
    usage: /sklep

  rynek:
    description: Otwiera rynek aukcji graczy.
    usage: /rynek

  wystaw:
    description: Wystawia trzymany przedmiot na rynek.
    usage: /wystaw <cena>
    aliases:
      - wystawprzedmiot